### ISSUE TITLE
Need Info about parallel run capability

### ISSUE THREAD

**Issue by vikramvi** [NativeScript/functional-tests-core#8]
Hi,

Can you please clarify below

1. if your framework support parallel run with help of selenium grid ? If yes how do you achieve it ?

2. I observed it has quite old appium java client version , any reason for including latest one ?

3. Do I need to use junit or testng ?

Thanks & Regards,
Vikram

**Comment by dtopuzov** [comment]
Hi Vikram,

Thanks for the interest in this framework.

1. Parallel execution:
We do not support parallel execution at the moment, however ti is possible to run multiple Jenkins jobs on the same machine. 
For example this can happen simultaneously (unless you are not on Windows host): 
Job1 clone tests based on this framework in workspace X and run against some Android emulator.
Job2 clone tests based on this framework in workspace Y and run against some iOS emulator.

2. Java Client
Appium Java Client 5.* is still beta and we use latest official. We will migrate to 5.* once it is official.

3. Junit or TestNG
Our base test is actually `testng` base test, so if you inherit our BaseTest you should use `testng`.
On theory it you use only APIs and do not inherit our BaseTest you should be able to use Junit.

Regards,
Dimitar

**Comment by vikramvi** [comment]
Hi Dimitar,

Thanks for detailed clarifications.

Regards,
Vikram
